#!/bin/bash -xv
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

cd ${OPENSHIFT_DATA_DIR}

# Set some defaults for variable that people can override.
# https://help.openshift.com/hc/en-us/articles/202399310
#   $ rhc set-env ASKNOT_THEME=default -a myapp
export ASKNOT_TEMPLATE=${ASKNOT_TEMPLATE:-templates/index.html}
export ASKNOT_QUESTION_FILE=${ASKNOT_QUESTION_FILE:-questions/fedora.yml}
export ASKNOT_STATIC_DIR=${ASKNOT_STATIC_DIR:-${OPENSHIFT_REPO_DIR}/static}
export ASKNOT_LOCALE_DIR=${ASKNOT_LOCALE_DIR:-${OPENSHIFT_REPO_DIR}/l10n/fedora/locale}
export ASKNOT_THEME=${ASKNOT_THEME:-fedora}

rm -rf build/
find ${OPENSHIFT_REPO_DIR}/.openshift/diy/. ! -name 'pythonserver.py' -exec rm -rf {} \;
rm -rf ${OPENSHIFT_DATA_DIR}/pip

VENV=${OPENSHIFT_DATA_DIR}venv
virtualenv ${VENV}
source ${VENV}/bin/activate

pip install \
    -r ${OPENSHIFT_REPO_DIR}/requirements.txt \
    -b ${OPENSHIFT_DATA_DIR}/pip \
    --log-file ${OPENSHIFT_DATA_DIR}/inst.log

# Install the thing to get the version number in place
python ${OPENSHIFT_REPO_DIR}/setup.py develop

echo "* Compiling translations"
${OPENSHIFT_REPO_DIR}/compile-translations.sh

echo "* Generating site"
# This would be cool.. but we need the server to ignore lots of stuff..
#echo "SEP: /" >> questions/fedora.yml
${OPENSHIFT_REPO_DIR}/asknot-ng.py \
    ${OPENSHIFT_REPO_DIR}/${ASKNOT_TEMPLATE} \
    ${OPENSHIFT_REPO_DIR}/${ASKNOT_QUESTION_FILE} \
    ${OPENSHIFT_REPO_DIR}/${ASKNOT_LOCALE_DIR} \
    -s ${ASKNOT_STATIC_DIR}/ \
    -t ${ASKNOT_THEME} \
    --fedmenu-url="https://apps.fedoraproject.org/fedmenu" \
    --fedmenu-data-url="https://apps.fedoraproject.org/js/data.js"


mv build/*                          ${OPENSHIFT_REPO_DIR}/.openshift/diy/.

echo "* Done"
