#!/bin/bash -xv
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

cd ${OPENSHIFT_DATA_DIR}

# Set some defaults for variable that people can override.
# https://help.openshift.com/hc/en-us/articles/202399310
#   $ rhc set-env ASKNOT_THEME=default -a myapp
ASKNOT_TEMPLATE=${ASKNOT_TEMPLATE:-templates/index.html}
ASKNOT_QUESTION_FILE=${ASKNOT_QUESTION_FILE:-questions/fedora.yml}
ASKNOT_STATIC_DIR=${ASKNOT_STATIC_DIR:-static}
ASKNOT_LOCALE_DIR=${ASKNOT_LOCALE_DIR:-locale}
ASKNOT_THEME=${ASKNOT_THEME:-fedora}

rm -rf build/
find ${OPENSHIFT_REPO_DIR}/.openshift/diy/. ! -name 'pythonserver.py' -exec rm -rf {} \;
rm -rf ${OPENSHIFT_DATA_DIR}/pip

VENV=${OPENSHIFT_DATA_DIR}venv
virtualenv ${VENV}
source ${VENV}/bin/activate

pip install \
    -r ${OPENSHIFT_REPO_DIR}/requirements.txt \
    -b ${OPENSHIFT_DATA_DIR}/pip \
    --log-file ${OPENSHIFT_DATA_DIR}/inst.log

# Install the thing to get the version number in place
python ${OPENSHIFT_REPO_DIR}/setup.py develop

echo "* Generating site"
# This would be cool.. but we need the server to ignore lots of stuff..
#echo "SEP: /" >> questions/fedora.yml
${OPENSHIFT_REPO_DIR}/asknot-ng.py \
    ${OPENSHIFT_REPO_DIR}/${ASKNOT_TEMPLATE} \
    ${OPENSHIFT_REPO_DIR}/${ASKNOT_QUESTION_FILE} \
    -s ${OPENSHIFT_REPO_DIR}/${ASKNOT_STATIC_DIR}/ \
    -L ${OPENSHIFT_REPO_DIR}/${ASKNOT_LOCALE_DIR}/ \
    -t ${ASKNOT_THEME}

mv build/*                          ${OPENSHIFT_REPO_DIR}/.openshift/diy/.

echo "* Done"
