on: push
#on:
#  push:
#    branches:
#      - develop
#  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Build the site
      run: |
        virtualenv --system-site-packages venv
        source venv/bin/activate
        python setup.py develop
        ./asknot-ng.py templates/index.html questions/fedora.yml l10n/fedora/locale --theme fedora
    - name: Push changes
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

        git clone https://user:$GITHUB_TOKEN@github.com/rh-impact/rh-impact.github.io

        mv build/* rh-impact.github.io/.
        cd rh-impact.github.io

        git add .
        git commit -m "Automated update from https://github.com/rh-impact/asknot-ng/actions"

        git push --set-upstream origin